#NumPy Learning

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,31,4,5], [2,3,4,5,6], [4,2,6,7,4]], np.int32)

In [3]:
myarr

array([[ 1,  2, 31,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 4,  2,  6,  7,  4]])

In [4]:
myarr[0, 2]

31

In [5]:
myarr.shape

(3, 5)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr

array([[ 1,  2, 31,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 4,  2,  6,  7,  4]])

In [8]:
myarr[0,2] = 3

In [9]:
myarr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 2, 6, 7, 4]])

In [10]:
myarr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 2, 6, 7, 4]])

In [11]:
np.array({45,45,23})

array({45, 23}, dtype=object)

In [12]:
zeros = np.zeros((10,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.size

50

In [15]:
zeros.dtype

dtype('float64')

In [16]:
zeros.shape

(10, 5)

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
rng[6]

6

In [20]:
rng.size

15

In [21]:
rng.shape

(15,)

In [22]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [23]:
emp = np.empty((5,3))

In [24]:
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
emp.size

15

In [26]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
lspace = np.linspace(1,4,6)

In [28]:
lspace

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [29]:
emp_like = np.empty_like(lspace)

In [30]:
emp_like

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [31]:
emp.shape

(5, 3)

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.shape

(99,)

In [35]:
arr = arr.reshape(3,33)

In [36]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr.ravel

<function ndarray.ravel>

In [38]:
arr = arr.ravel()

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr = arr.reshape(3,33)

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.shape

(3, 33)

In [44]:
arr = arr.ravel()

In [45]:
arr.shape

(99,)

In [46]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [47]:
ar = np.array(x)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis=0)

array([12,  8,  9])

In [50]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [51]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [52]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [53]:
for item in ar:
    for j in item:
        print(j)

1
2
3
4
5
6
7
1
0


In [54]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [55]:
ar.ndim

2

In [56]:
ar.size

9

In [57]:
ar.shape

(3, 3)

In [58]:
ar.nbytes

36

In [59]:
ar.argmax

<function ndarray.argmax>

In [60]:
ar.argmax()

6

In [61]:
one = np.array([23,4,5,3,32,2])

In [62]:
one.argmax()

4

In [63]:
one.argmin()

5

In [64]:
one.argsort()

array([5, 3, 1, 2, 0, 4], dtype=int64)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.argmax

<function ndarray.argmax>

In [67]:
ar.argmax()

6

In [68]:
ar.argmin()

8

In [69]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [70]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [71]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [72]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [73]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [76]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
ar2 = np.array([[3, 6, 7],
       [2, 5, 8],
       [4, 8, 9]])

In [81]:
ar + ar2

array([[ 4,  8, 10],
       [ 6, 10, 14],
       [11,  9,  9]])

In [82]:
ar * ar2

array([[ 3, 12, 21],
       [ 8, 25, 48],
       [28,  8,  0]])

In [83]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [84]:
ar / ar2

array([[0.33333333, 0.33333333, 0.42857143],
       [2.        , 1.        , 0.75      ],
       [1.75      , 0.125     , 0.        ]])

In [85]:
ar - ar2

array([[-2, -4, -4],
       [ 2,  0, -2],
       [ 3, -7, -9]])

In [86]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [87]:
np.sum(ar)

29

In [88]:
np.max(ar)

7

In [89]:
np.min(ar)

0

In [90]:
ar.max()

7

In [91]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [92]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [93]:
type(ar)

numpy.ndarray

In [94]:
np.count_nonzero(ar)

8

In [95]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [96]:
ar[1,2] = 0

In [97]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [98]:
import sys

In [99]:
py_ar = [0,4, 55, 2]

In [100]:
np_ar = np.array(py_ar)

In [101]:
np_ar

array([ 0,  4, 55,  2])

In [102]:
sys.getsizeof(1) * len(py_ar)

112

In [103]:
sys.getsizeof(1) * np_ar.size

112

In [104]:
np_ar.itemsize * np_ar.size

16

In [105]:
np_ar

array([ 0,  4, 55,  2])

In [106]:
list(np_ar)

[0, 4, 55, 2]

In [107]:
np_ar.tolist

<function ndarray.tolist>

In [108]:
np_ar.tolist()

[0, 4, 55, 2]

In [109]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [110]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0]], dtype=int64)

In [160]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [161]:
new_ar = np.array(x)

In [123]:
new_ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
for items in new_ar.flat:
    print(items)

1
2
3
4
5
6
7
8
9


In [128]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [129]:
np.empty((3,2))

array([[1. , 1.6],
       [2.2, 2.8],
       [3.4, 4. ]])

In [130]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [131]:
new_ar.size

9

In [132]:
new_ar.shape

(3, 3)

In [134]:
new_ar.dtype

dtype('int32')

In [136]:
new_ar.max()

9

In [137]:
new_ar.min()

1

In [139]:
new_ar.sum(axis=0)

array([12, 15, 18])

In [143]:
new_ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [145]:
new_ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [151]:
new_ar

array([[ 1, 32,  3],
       [ 4,  5, 12],
       [43,  8,  9]])

In [150]:
new_ar[2,0] = 43

In [154]:
np.count_nonzero(new_ar)

9

In [155]:
new_ar.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [162]:
np.where(new_ar > 5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [165]:
new_ar.ravel().tolist()

In [168]:
new2_ar = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [169]:
new_ar + new2_ar

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [170]:
new_ar * new2_ar

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])